#The following options are as follows:
#True: When user has restricted chest access this option will stop them from opening said item.
#False: Allows user to open said chest even with chest access restricted.
#Default is True.

ChestItem: true
EnderChestItem: true

PickUpMessage: You cannot pickup items.
PickUpMessageToggle: false

ThrowMessage: You cannot throw items.
ThrowMessageToggle: true

ChestMessage: You cannot open this.
ChestMessageToggle: true

DropMessage: Your items have vanished upon your death.
DropMessageToggle: true