name: AdminDrop
version: 0.5.0.0
description: Restricts item interactions.
author: pyropyro78
main: com.pyromanticgaming.admindrop.AdminDrop
commands:
   ad:
      description: The goal of this plugin is to handle all item actions (Dropping, Throwing, Picking Up, etc.).
      usage: |
        /ad deathdrop - Toggles Death Drops on/off
        /ad deathdrop [player] - Toggles other's Death Drops on/off
        /ad throwaway - Toggles the ability to throw away items on/off
        /ad throwaway [player] - Toggles other's throw away items on/off
        /ad pickup - Toggles the ability to pick up items on/off
        /ad pickup [player] - Toggles other's ability to pick up items on/off
        /ad chestaccess - Toggles the ability to open chests on/off
        /ad chestaccess [player] - Toggles other's ability to open chests on/off
        /ad status - Gets current status
        /ad status [player] - Gets players current status
        /ad help - Displays commands
        /ad alt - Shows alternate commands